// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: ratelimiter.proto

package ratelimiter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RatelimiterPushSlidingWindowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Max      int64  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *RatelimiterPushSlidingWindowRequest) Reset() {
	*x = RatelimiterPushSlidingWindowRequest{}
	mi := &file_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatelimiterPushSlidingWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatelimiterPushSlidingWindowRequest) ProtoMessage() {}

func (x *RatelimiterPushSlidingWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatelimiterPushSlidingWindowRequest.ProtoReflect.Descriptor instead.
func (*RatelimiterPushSlidingWindowRequest) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *RatelimiterPushSlidingWindowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RatelimiterPushSlidingWindowRequest) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type RatelimiterPushSlidingWindowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *RatelimiterPushSlidingWindowResponse) Reset() {
	*x = RatelimiterPushSlidingWindowResponse{}
	mi := &file_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatelimiterPushSlidingWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatelimiterPushSlidingWindowResponse) ProtoMessage() {}

func (x *RatelimiterPushSlidingWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatelimiterPushSlidingWindowResponse.ProtoReflect.Descriptor instead.
func (*RatelimiterPushSlidingWindowResponse) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *RatelimiterPushSlidingWindowResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *RatelimiterPushSlidingWindowResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_ratelimiter_proto protoreflect.FileDescriptor

var file_ratelimiter_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72,
	0x22, 0x53, 0x0a, 0x23, 0x52, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x6c, 0x69, 0x64, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x60, 0x0a, 0x24, 0x52, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x53, 0x6c, 0x69, 0x64, 0x69, 0x6e, 0x67, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x89, 0x01, 0x0a, 0x0b, 0x52, 0x61, 0x74, 0x65,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x12, 0x7a, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x53,
	0x6c, 0x69, 0x64, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x30, 0x2e, 0x72,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x53, 0x6c, 0x69, 0x64, 0x69, 0x6e,
	0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31,
	0x2e, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x53, 0x6c, 0x69, 0x64,
	0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ratelimiter_proto_rawDescOnce sync.Once
	file_ratelimiter_proto_rawDescData = file_ratelimiter_proto_rawDesc
)

func file_ratelimiter_proto_rawDescGZIP() []byte {
	file_ratelimiter_proto_rawDescOnce.Do(func() {
		file_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_ratelimiter_proto_rawDescData)
	})
	return file_ratelimiter_proto_rawDescData
}

var file_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimiter_proto_goTypes = []any{
	(*RatelimiterPushSlidingWindowRequest)(nil),  // 0: ratelimiter.RatelimiterPushSlidingWindowRequest
	(*RatelimiterPushSlidingWindowResponse)(nil), // 1: ratelimiter.RatelimiterPushSlidingWindowResponse
}
var file_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.Ratelimiter.PushSlidingWindow:input_type -> ratelimiter.RatelimiterPushSlidingWindowRequest
	1, // 1: ratelimiter.Ratelimiter.PushSlidingWindow:output_type -> ratelimiter.RatelimiterPushSlidingWindowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ratelimiter_proto_init() }
func file_ratelimiter_proto_init() {
	if File_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ratelimiter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimiter_proto_goTypes,
		DependencyIndexes: file_ratelimiter_proto_depIdxs,
		MessageInfos:      file_ratelimiter_proto_msgTypes,
	}.Build()
	File_ratelimiter_proto = out.File
	file_ratelimiter_proto_rawDesc = nil
	file_ratelimiter_proto_goTypes = nil
	file_ratelimiter_proto_depIdxs = nil
}
